### ISSUE TITLE
Feature: manual pricing & group order

### ISSUE THREAD

**Issue by srobi** [recursivetree/seat-alliance-industry#1]
(1) allow to price the order manually (not linked to Jita buy/sell+profit)
(2) allow group order - multiple item and fulfilment expected only in full (e.g. ordering a ship+fit as a group order and delivery should be all modulers/rigs/hull) from the same party, same time

[it is already a quite nice tool]

**Comment by recursivetree** [comment]
(1) is possible, I was just too lazy to write the documentation. A description on how to do it is in the patch notes. https://github.com/recursivetree/seat-alliance-industry/releases/tag/1.0.4 
(2) is something I don't plan on adding any time soon. The plugin is primarily made for my alliance, and we don't need it. If it was a smaller feature, I'm pretty sure I would add it for you, but it's a kinda huge change. You can still submit a pr and I'll consider it(if you do so, please contact me with details before programming it make sure it will get accepted). We could also work out a deal where I add the feature for a payment(Prob in a range of 1-2b, depending on details). 

If you want to order a ship and fit, you can add all items into the text area and it will create separate orders for each, in case you didn't know.

Example:
```
Tristan 100
Warrior 500
Medium Shield Extender I 100
```

**Comment by srobi** [comment]
(1) Installed: v1.0.4 and if I insert the exact example it returns with different pricing (I assumed Jita). screenshots:
https://gyazo.com/f90d25d0e7246cc241d466470d532ce9
https://gyazo.com/c3c78c40af58fcb3c35457dee06c4353

(2)I'll revert soon

**Comment by recursivetree** [comment]
1) To prevent scams, the price can't be lower than the automatic price. Additionally, the profit % is applied on top of the manual price

**Comment by recursivetree** [comment]
> 1. To prevent scams, the price can't be lower than the automatic price. Additionally, the profit % is applied on top of the manual price

With the latest version, there are new settings to configure both behaviours.
