### ISSUE TITLE
BUG: Can not delete order

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#13]
![Screenshot 2023-01-11 at 1 56 26](https://user-images.githubusercontent.com/46750448/211693285-39ba56f4-5409-45a4-bf1b-64ad1f8977eb.png)

I would expect that orders which are pass the expiry date will disappear. Did not happen here. Order is 3 days expired and still there. Wanted to manually delete him but no success. Delete button is not there. Not from his UI or from admin UI.

Might be connected to the latest changes with UPDATE PRICE button. This button was used here.

**Comment by recursivetree** [comment]
yes, that is a bug. If you delete the delivery, you should be able to delete it

**Comment by recursivetree** [comment]
It will be fixed with the next release

**Comment by martinskalicky** [comment]
I do confirm the fix
