### ISSUE TITLE
FEATURE: Changing Completed Row in OR

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#14]
hello,

I do believe that Completed column in Open Orders does not really give any value. Its always not completed and when it is it will dissappear.

Changing this to when order was created might give better value so u can sort it by newest (if u checked all old orders).

**Comment by recursivetree** [comment]
That is indeed the case. Open order=not completed. Rather than having it sorted by creation date, I'd suggest priority(and maybe creation date within the same priority)

**Comment by recursivetree** [comment]
But if you want to sort by creation date, I can add that

**Comment by martinskalicky** [comment]
Point is that "create date" row is missing now
