### ISSUE TITLE
FEATURE: Set destinations manually 

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#18]
Hello,

ability to set destinations instead of picking from the list.

Why?

Well u do deliver items and u are aware where u will deliver items or where u can deliver them. It makes bigger sense that u will set destinations where u can deliver items instead of picking any location from requestor.

Its just easier if u are doing 3-4 locations (stagings) then picking from very huge list

Martin

**Comment by recursivetree** [comment]
I don't understand what you mean. destinations don't make sense in the context of seat-alliance-industry

**Comment by martinskalicky** [comment]
![Screenshot 2023-02-02 at 11 45 51](https://user-images.githubusercontent.com/46750448/216304224-cae783f9-3409-4815-8635-2b283b051874.png)

If we would be able to set which locations we do support for orders that would be super-cool. Usual use-case is that we do support few locations (stagings) instead of all locations in EVE. 

Sorry for lack of description before.

**Comment by recursivetree** [comment]
I'll consider it

**Comment by recursivetree** [comment]
Instead of locking down the options, I think people can just ignore orders at locations they can't produce at
