### ISSUE TITLE
FEATURE: Auto-delete orders if they are past due

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#19]
Hello,

currently orders which no-one picked up are still in orders. I suggest they should expire (if no-one picked them up) and they should be removed from the list.

Martin

**Comment by recursivetree** [comment]
I don't think they should be deleted, but what I'd suggest is removing them from the open orders list, but leaving them on the "your orders" list, with a button to refresh dates

**Comment by martinskalicky** [comment]
I see what u mean and I do think its great idea!

**Comment by recursivetree** [comment]
done, will come with the next release
