### ISSUE TITLE
Adding one column to "Your Deliveries"

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#2]
Would it be possible to add to screen **"Your Deliveries"** column with a name of the pilot who ordered stuff?
U get can information by clicking on item name however that is very time-consuming if u are finishing **100 orders or more**.
We are heavily using this plugin and it would be really great if we can make that change. I believe its not an issue if u have few big orders, but our use case is small orders but hundreds of them.

I would imagine "Ordered By" and current Character could be "Manufacturer".
However main point is to add a person who ordered that item to that screen.

**Comment by recursivetree** [comment]
It should be possible to add an "ordered by" column.

**Comment by martinskalicky** [comment]
Thank you that would be awesome!

**Comment by recursivetree** [comment]
Changes are committed, it will come out with the next release
