### ISSUE TITLE
BUG: ISK price after update

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#22]
Hello,

we had order 100/130 and we clicked "UPDATE PRICE" and price went to astronomic numbers. There is a bug in calculation.

Steps to reproduce:
1) Create order
2) Deliver some part of that
3) Click update price

U will see nonsense numbers.

--Martin

**Comment by recursivetree** [comment]
I can't reproduce the issue. Can you provide me with the items of the order in question, the default price provider from settings and the price provider used at order creation?

**Comment by martinskalicky** [comment]
This can be closed. I assume, I will re-open. If we will have same issue
