### ISSUE TITLE
FEATURE: Cancel delivery/order

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#23]
Hello,

we are facing problems with orders which are "stucked".

If order is 300/300 filled. But last delivery guy forget to "change" his order to "delivered" order is stuck there and even owner can not delete him.

Can we set up some timeframe when u need to delivery it and if u dont your delivery will be canceled?
We do not any chance to help ourself here. Only reason is to inherit to the user and manually fixed that. However that is not a solution if u are working with thousands of orders with different groups.

--Martin

**Comment by recursivetree** [comment]
It is intentional that orders can't be closed until deliveries are fulfilled. The idea is that nobody can create scam orders, let people produce things and while they produce it, you cancel the order.

That is, I'm sure we can make missing the deadline actually matter in one way or another.

**Comment by recursivetree** [comment]
If you really have a ton of stuck orders, an admin can always delete orders if I'm right

**Comment by martinskalicky** [comment]
Admin can delete orders, however this is not experience. If we can setup some deadline that could be great.

Can we do deadline and if its missed it will be canceled?

**Comment by recursivetree** [comment]
I added an option that deletes unfulfilled orders after they expire. It will come with the next release
