### ISSUE TITLE
Add another price provider

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#24]
Hello,

as evepraisal is gone can we replaced it with for example Janice version?

Martin

**Comment by recursivetree** [comment]
Seat 5 will price the new seat prices system to alliance industry, so I'm not sure if it is worth to invest in a janice price provider

**Comment by martinskalicky** [comment]
A lot of people is still using Seat 4 as Seat 5 is still under development most of the plugins does not have stable version for Seat 5.

**Comment by recursivetree** [comment]
I know, I'm just wondering whether the effort to write the janice provider should rather go to finishing seat 5. It is basically finished besides merging a few PRs and writing some documentation.

**Comment by recursivetree** [comment]
Closing this as development will focus on seat 5 going forward
