### ISSUE TITLE
Price bug + price question

### ISSUE THREAD

**Issue by hermesdj** [recursivetree/seat-alliance-industry#25]
Hi @recursivetree 

I think I got a bug on the price in controller function submitOrder (line 68+). The price provider when it sets the price (I use evepraisal) set it at the individual price * amount, so in alliance industry an item price should be $price / $amount. Is it standard behavior for all price provider to do that, or is it just the evepraisal one ?

If it's standard, then alliance industry should fix how it compute the price for individual items.

In the code, I also see on the items a manualPrice and a marketPrice property being used to override the price provided by the price provider. How do the user fill the manual price value ? And where does it fill the marketPrice property ? The price provider does not do that, neither the parser from seat-treelib. The Multibuy parser will set the property ingamePrice but the fitting parser set only the amount. It works but I was wondering if something was missing from previous versions or if it's the price provider that should fill some of these values ?

**Comment by recursivetree** [comment]
Thanks for the report, I missed it because it seems like I never tested ordering multiple items after upgrading to seat 5.

manualPrices is set by the parser, specifically the `ManualBuyParser`. You can specify manual prices by adding the price after the item and amount, e.g. `Omen 1 4 ISK` to buy an Omen for 4 ISK. `marketPrice` is another thing that got broken during the seat 5 migration and needs to be fixed.

**Comment by recursivetree** [comment]
Should be fixed in release 2.0.2

**Comment by zenobio93** [comment]
@recursivetree It seems not be fixed. But maybe it's just an price provider issue while we using janice as price provider?

<img width="1156" alt="Bildschirmfoto 2024-03-04 um 12 27 17" src="https://github.com/recursivetree/seat-alliance-industry/assets/5907705/ede6c7f2-4ca8-42cb-8d86-8532cb67f6da">

as you can see in Screenshot, the single Price should be the total price and the total price is here the normally total price * amount.

**Comment by recursivetree** [comment]
thanks for the report, it should be fixed in v2.0.3

**Comment by zenobio93** [comment]
Looks good for me. Thanks
