### ISSUE TITLE
Ability to order full fit

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#3]
You do have also plugin which is checking inventory of alliance/corp and there is possibility to check full fits and then order them using this plugin.

Would it be possible to add feature so u can order full fits which can be read from seat-fittings? That would make our life so much easier, cause people do mistakes and we have a lot of "System#" orders which we need to clean daily

**Comment by recursivetree** [comment]
You can do that with seat-inventory. There is an "order with seat-alliance-industry" button in the stock info popup which orders missing items.

Regarding "System#" orders, how do you get them? That seems like a bug that I haven't encountered yet.

**Comment by martinskalicky** [comment]
You can do that however that works if u want to order for alliance/corporation. But wont work for individual people. Our use-case is if they want to bring any fits, they do order with plugin. Right now they have to do it one-by-one.

I will gather reproduction steps and get back to you on that.

**Comment by recursivetree** [comment]
The parser now understand multibuys and fittings. You should be able to test it by installing the latest version
