### ISSUE TITLE
Feature: saving filters presets

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#6]
Hello,

when we are working with the tool and we for example filter by player, it resets everytime we go back to default window. If we can save it so we dont have to apply filters all over again that would help a lot.

This comes with "show entries (10/25/50/100) this also resets every single time when we change window.

It might not been seen as a problem. However when we are having a lot of orders its sometimes too much clicks.

Martin

**Comment by recursivetree** [comment]
That seems like a useful feature, yes. I'm not sure it is doable with the library used by seat for the fancy tables though. I'll investigate it.

**Comment by martinskalicky** [comment]
Thank you for your time looking into this one. It's not something we are unhappy everyday but for sure it will make our experience much better (We are really heavily using this plugin).

**Comment by recursivetree** [comment]
actually, the table library supports it. I enabled it for all tables
