### ISSUE TITLE
HOTFIX: Can not select correct station to receive items

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#7]
Hello,

after latest change I'm not able to select "Haimeh Wiyrkomi Corporation Factory". I'm able just to select CBD one.

Current solution is dropdown menu and not textbox as before so we cant write it there manually anymore.

**Comment by recursivetree** [comment]
I'm a bit confused. Are you able to select it or not? Or is the problem that it doesn't appear? Are these citadels or NPC stations(I assume so). Can you also provide the system, so I can check if it happens with me too?

**Comment by martinskalicky** [comment]
Haimeh VII - Wiyrkomi Corporation Factory - when im trying to find it in dropdown menu, I'm always able to filter only Haimeh CBD corporation factory.

System: Haimeh
Station: NPC

My problem is to find it in the list, filtering thrue "H" will get me only to CBD corporation factory.

**Comment by martinskalicky** [comment]
![Screenshot 2023-01-02 at 19 22 41](https://user-images.githubusercontent.com/46750448/210267420-505035a3-ca15-4962-bf4f-efd709a6ac01.png)

**Comment by recursivetree** [comment]
fixed, I'll release the hotfix after I'll finish your other issue
