### ISSUE TITLE
HOTFIX: Ordering more items does not work

### ISSUE THREAD

**Issue by martinskalicky** [recursivetree/seat-alliance-industry#9]
### Steps to reproduce:
![Screenshot 2023-01-03 at 14 17 39](https://user-images.githubusercontent.com/46750448/210364920-4c5e27e7-2ab3-4dbf-8b29-1fbfcf568291.png)
![Screenshot 2023-01-03 at 14 18 02](https://user-images.githubusercontent.com/46750448/210364928-d0dc5175-186e-4731-b5f2-ca170e849e36.png)
![Screenshot 2023-01-03 at 14 18 25](https://user-images.githubusercontent.com/46750448/210364940-f5257056-185b-4373-8d86-2db5aa323e4d.png)

**Comment by martinskalicky** [comment]
Running on latest version **v1.1.7**
EDIT: Tried several items by now, all works the same, you can not order more then one item.

**Comment by recursivetree** [comment]
fixed it, sorry for the inconvenience. As I currently don't run any seat instance, it's sometimes difficult to find issues like this.
